Camada.Aplicacao/Controllers/LISTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Camada.Dominio.Entidades;
using iTextSharp.text;
using System.IO;
using Library.Utilities;
using Camada.Dominio;
using Library.Messages;
using System.Web.Routing;

namespace Camada.Aplicacao.Controllers
{
    public class LISTsController : Controller
    {
        private HostelEntities db = new HostelEntities();

        //Upload image
        public ActionResult FileUpload(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                string pic = System.IO.Path.GetFileName(file.FileName);

                byte[] uploadedFile = new byte[file.InputStream.Length];
                file.InputStream.Read(uploadedFile, 0, uploadedFile.Length);

                int id = Convert.ToInt32(Request["ID"]);
                var list = db.LISTs.Where(w => w.ID == id).FirstOrDefault();
                var msgL = new LIST();

                var doc = new DOCUMENT();
                doc.DT_INSERT = DateTime.UtcNow;
                doc.FILE_CONTENT = uploadedFile;
                doc.FILE_NAME = list.LAST_NAME_GUEST;
                doc.FILE_TYPE = file.FileName.Split('.')[1];

                var msgDoc = Fachada.Negocio.ManterDOCUMENT.Save(doc);
                if (msgDoc.Result != Message.ResultType.Success)
                    return Content(msgDoc.Description);

                msgL.ID = list.ID;
                msgL.ID_LIST_TYPE = list.ID_LIST_TYPE;
                msgL.DT_START_BLOCK = list.DT_START_BLOCK;
                msgL.DT_START_BOOK = list.DT_START_BOOK;
                msgL.FIRST_NAME_GUEST = list.FIRST_NAME_GUEST;
                msgL.LAST_NAME_GUEST = list.LAST_NAME_GUEST;
                msgL.LOGLOGIN = list.LOGLOGIN;
                msgL.NOTES = Convert.ToString(Request["txtNotes"]);
                msgL.ID_DOCUMENT = doc.ID;

                var msgSaveList = Fachada.Negocio.ManterLIST.Save(msgL);
                if (msgSaveList.Result != Message.ResultType.Success)
                    return Content(msgSaveList.Description);

                return RedirectToAction("IndexVerifyBooking");
            }

            return RedirectToAction("EditVerifyBooking", "LISTS", new { id = Convert.ToInt32(Request["ID"]), uploadImage = true });

        }

        public ActionResult FileUploadBlacklist(HttpPostedFileBase file)
        {
            var firstName = Convert.ToString(Request["FIRST_NAME_GUEST"]);
            var lastName = Convert.ToString(Request["LAST_NAME_GUEST"]);
            var doc = new DOCUMENT();

            if (file != null && file.ContentLength > 0)
            {
                string pic = System.IO.Path.GetFileName(file.FileName);

                byte[] uploadedFile = new byte[file.InputStream.Length];
                file.InputStream.Read(uploadedFile, 0, uploadedFile.Length);

                doc.DT_INSERT = DateTime.UtcNow;
                doc.FILE_CONTENT = uploadedFile;
                doc.FILE_NAME = lastName;
                doc.FILE_TYPE = file.FileName.Split('.')[1];

                var msgDoc = Fachada.Negocio.ManterDOCUMENT.Save(doc);
                if (msgDoc.Result != Message.ResultType.Success)
                    return Content(msgDoc.Description);
            }

            var msgL = new LIST();
            if (!string.IsNullOrEmpty(Request["CHECK_IN"]))
                msgL.CHECK_IN = Convert.ToDateTime(Request["CHECK_IN"]);
            if (!string.IsNullOrEmpty(Request["CHECK_OUT"]))
                msgL.CHECK_OUT = Convert.ToDateTime(Request["CHECK_OUT"]);

            if (!string.IsNullOrEmpty(Request["NOTES"]))
                msgL.NOTES = Convert.ToString(Request["NOTES"]);

            msgL.ID_LIST_TYPE = (int)TabList_Type.BLACKLIST;
            msgL.FIRST_NAME_GUEST = firstName;
            msgL.LAST_NAME_GUEST = lastName;
            msgL.LOGLOGIN = User.Identity.Name;
            if (doc.ID > 0)
                msgL.ID_DOCUMENT = doc.ID;

            var msgSaveList = Fachada.Negocio.ManterLIST.Save(msgL);
            if (msgSaveList.Result != Message.ResultType.Success)
                return Content(msgSaveList.Description);

            return RedirectToAction("IndexBlacklist");
        }

        public string getLastFirstName(string txtCopied)
        {
            string listLastFirstName = string.Empty;

            string[] splitTxtCopied = txtCopied.Split(new String[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);
            int countSplit = 0;
            DateTime dtTest = DateTime.Now;

            foreach (string row in splitTxtCopied)
            {
                if (countSplit == 0 && DateTime.TryParse(row, out dtTest))
                {
                    countSplit++;
                    continue;
                }
                else if (countSplit == 0)
                    continue;
                else if (countSplit == 1)
                {
                    if (!string.IsNullOrEmpty(row))
                        listLastFirstName += row.Trim() + "|";

                    countSplit++;
                    continue;
                }
                else if (countSplit == 2 || countSplit == 3 || countSplit == 4)
                {
                    if (countSplit == 4)
                    {
                        countSplit = 1;
                        continue;
                    }
                    countSplit++;
                    continue;
                }
            }

            return listLastFirstName.Remove(listLastFirstName.Length - 1, 1);
        }

        //getGrid
        private JsonResult getJsonResult(string sEcho, int iDisplayStart, int iDisplayLength, string sSortDir_0, int iSortCol_0, int ID_LIST_TYPE)
        {
            var firstName = Convert.ToString(Request["txtFirstName"]);
            var lastName = Convert.ToString(Request["txtLastName"]);
            var lastFirstName = Convert.ToString(Request["txtCopied"]);
            string[] listLastFirstName = new string[] { };
            if (!string.IsNullOrEmpty(lastFirstName))
                listLastFirstName = lastFirstName.Split('|');

            var displayedCompanies = Fachada.Repositorio.LIST.GetAllListsByFilter(new Dominio.Mensagens.Filtro.Lists
            {
                //Dados Padrão da Paginação Coluna Clicada, Ordenação ASC DESC, Skip, Take, 
                iDisplayStart = iDisplayStart,
                iDisplayLength = iDisplayLength,
                sSortDir_0 = sSortDir_0,
                iSortCol_0 = iSortCol_0,
                ID_LIST_TYPE = ID_LIST_TYPE,
                firstName = firstName,
                lastName = lastName,
                lastFirstName = listLastFirstName
            });


            string pastaImages = @"~/Images/Profile/";
            string folderServerMapPath = string.Empty;

            folderServerMapPath = Server.MapPath(pastaImages);
            if (!Directory.Exists(folderServerMapPath))
                Directory.CreateDirectory(folderServerMapPath);

            foreach (var item in displayedCompanies.Instances)
            {
                string url = string.Empty;
                string altText = item.LAST_NAME_GUEST;

                string physicalPath = Path.Combine(folderServerMapPath, item.FullFileName);

                DirectoryInfo diDocument = new DirectoryInfo(folderServerMapPath);
                if (diDocument.Exists)
                {
                    bool existe = false;
                    foreach (var iD in diDocument.GetFiles())
                    {
                        if (iD.Name == item.FullFileName)
                        {
                            existe = true;
                            break;
                        }
                    }
                    if (!existe)
                        System.IO.File.WriteAllBytes(physicalPath, item.FILE_CONTENT);
                }

                var qUrl = Url.Content(Path.Combine(pastaImages, item.FullFileName));
                item.htmlImage = string.Format("<img src=\"{0}\" alt=\"{1}\" id=\"puscicaL_0\" class=\"puscica puscical\" style=\"opacity:1;width:120px;\" />", qUrl, altText);
            }

            IEnumerable<string[]> result = Enumerable.Empty<string[]>();
            if (ID_LIST_TYPE == (int)TabList_Type.VERIFY_BOOKING)
            {
                result = (from l in displayedCompanies.Instances
                          select new[] {
                                            l.ID.ToString(),
                                            l.LOGLOGIN,
                                            l.FullName,
                                            l.DT_START_BLOCK.Value.ToString("dd/MM/yyyy"),
                                            l.DT_START_BOOK.Value.ToString("dd/MM/yyyy"),
                                            l.NOTES,
                                            l.htmlImage
                            }).Take(iDisplayLength);
            }
            else if (ID_LIST_TYPE == (int)TabList_Type.BLACKLIST)
            {
                result = (from l in displayedCompanies.Instances
                          select new[] {
                                            l.ID.ToString(),
                                            l.LOGLOGIN,
                                            l.FullName,
                                            l.CHECK_IN.HasValue ? l.CHECK_IN.Value.ToString("dd/MM/yyyy") : "",
                                            l.CHECK_OUT.HasValue ? l.CHECK_OUT.Value.ToString("dd/MM/yyyy"): "",
                                            l.NOTES,

Camada.Aplicacao/Views/LISTs/Create.cshtml
@model Camada.Dominio.Entidades.LIST

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("FileUpload", "LISTs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <label for="file">Upload Image:</label>
    <input type="file" name="file" id="file" style="width: 100%;" />
    <input type="submit" value="Upload" class="submit" />

    <div class="form-horizontal">
        <h4>LIST</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.ID_LIST_TYPE, "ID_LIST_TYPE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_LIST_TYPE", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_LIST_TYPE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CHECK_IN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CHECK_IN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CHECK_IN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CHECK_OUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CHECK_OUT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CHECK_OUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DT_START_BLOCK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DT_START_BLOCK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DT_START_BLOCK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DT_START_BOOK, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DT_START_BOOK, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DT_START_BOOK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NOTES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOTES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOTES, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DOCUMENT.NAME_GUEST, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOCUMENT.NAME_GUEST, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOCUMENT.NAME_GUEST, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.LOGLOGIN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LOGLOGIN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LOGLOGIN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Camada.Aplicacao/Views/LISTs/CreateBlacklist.cshtml
@model Camada.Dominio.Mensagens.TelaLISTs
@{
    ViewBag.Title = "Create";
}

<h2><i class="fa fa-pencil"></i> Create</h2>
<div class="form-horizontal">
    <h4>Blacklist</h4>
</div>

@using (Html.BeginForm("FileUploadBlacklist", "LISTs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">

            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.FIRST_NAME_GUEST, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.FIRST_NAME_GUEST, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.FIRST_NAME_GUEST, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LAST_NAME_GUEST, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.LAST_NAME_GUEST, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.LAST_NAME_GUEST, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CHECK_IN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CHECK_IN, new { htmlAttributes = new { @class = "form-control dateTextField" } })
                    @Html.ValidationMessageFor(model => model.CHECK_IN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CHECK_OUT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CHECK_OUT, new { htmlAttributes = new { @class = "form-control dateTextField" } })
                    @Html.ValidationMessageFor(model => model.CHECK_OUT, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NOTES, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.TextAreaFor(model => model.NOTES, new { htmlAttributes = new { @class = "form-control" }, @cols = 100 })
                    @Html.ValidationMessageFor(model => model.NOTES, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <label for="file">Upload Image:</label>
                    <input type="file" name="file" id="file" style="width: 100%;" />

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Create
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("IndexBlacklist", "LISTs")'"
                            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-arrow-left"></i> &nbsp;
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
}

<script language="javascript" type="text/javascript">
    function h(e) {
        $(e).css({ 'height': 'auto', 'overflow-y': 'hidden' }).height(e.scrollHeight);
    }
    $('textareafor').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>

Camada.Aplicacao/Views/LISTs/CreateVerifyBooking.cshtml
@{
    ViewBag.Title = "Create";
}

<h2><i class="fa fa-pencil"></i> Create</h2>
<div class="form-horizontal">
    <h4>Verify Booking</h4>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">

            <hr />

            <div class="form-group">
                <div class="col-md-13">
                    <label for="txtCopied" class="col-sm-1 control-label">Past the Sheet here:</label>
                    <div class="col-sm-10">
                        @Html.TextArea("txtCopied", new { htmlAttributes = new { @class = "form-control pastSheet", required = "required" }, @cols = 140 })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <label for="txtDays" class="col-sm-2 control-label">How many days:</label>
                    <div class="col-sm-3">
                        <input type="text" style="width: 100px;" name="txtDays" class="form-control sm" id="txtDays" required>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Create
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("IndexVerifyBooking", "LISTs")'"
                            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-arrow-left"></i> &nbsp;
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
}

<script language="javascript" type="text/javascript">
    function h(e) {
        $(e).css({'height':'auto','overflow-y':'hidden'}).height(e.scrollHeight);
    }
    $('textarea').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>

Camada.Aplicacao/Views/LISTs/EditBlacklist.cshtml
@model Camada.Dominio.Mensagens.TelaLISTs
@{
    ViewBag.Title = "Edit";
}

<h2><i class="fa fa-pencil"></i> Edit</h2>
<div class="form-horizontal">
    <h4>Blacklist</h4>
</div>

@using (Html.BeginForm("FileUploadBlacklist", "LISTs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">

            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.FIRST_NAME_GUEST, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.FIRST_NAME_GUEST, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.FIRST_NAME_GUEST, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.LAST_NAME_GUEST, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.EditorFor(model => model.LAST_NAME_GUEST, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.LAST_NAME_GUEST, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CHECK_IN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CHECK_IN, new { htmlAttributes = new { @class = "form-control dateTextField" } })
                    @Html.ValidationMessageFor(model => model.CHECK_IN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CHECK_OUT, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CHECK_OUT, new { htmlAttributes = new { @class = "form-control dateTextField" } })
                    @Html.ValidationMessageFor(model => model.CHECK_OUT, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NOTES, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-5">
                    @Html.TextAreaFor(model => model.NOTES, new { htmlAttributes = new { @class = "form-control" }, @cols = 100 })
                    @Html.ValidationMessageFor(model => model.NOTES, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <label for="file">Upload Image:</label>
                    <input type="file" name="file" id="file" style="width: 100%;" />

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Create
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("IndexBlacklist", "LISTs")'"
                            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-arrow-left"></i> &nbsp;
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
}

<script language="javascript" type="text/javascript">
    function h(e) {
        $(e).css({ 'height': 'auto', 'overflow-y': 'hidden' }).height(e.scrollHeight);
    }
    $('textareafor').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>

Camada.Aplicacao/Views/LISTs/EditVerifyBooking.cshtml

@{
    ViewBag.Title = "Create";
}

<h2><i class="fa fa-pencil"></i> Edit</h2>
<div class="form-horizontal">
    <h4>Verify Booking</h4>
</div>

@using (Html.BeginForm("FileUpload", "LISTs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">
            @Html.Hidden("ID")
            <hr />
            @if (ViewBag.uploadImage)
            {
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="file">Upload Image:</label>
                        <input type="file" name="file" id="file" style="width: 100%;" />

                    </div>
                </div>
                @*<div class="form-group">
                    <div class="col-md-4">
                        <input type="submit" value="Upload" class="submit" />
                    </div>
                </div>*@
            }


            <div class="form-group">
                <div class="col-md-13">
                    <label for="txtNotes" class="col-sm-1 control-label">Notes:</label>
                    <div class="col-sm-10">
                        @Html.TextArea("txtNotes", new { htmlAttributes = new { @class = "form-control pastSheet" }, @cols = 100 })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Save
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("Index", "LISTs")'"
                            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-arrow-left"></i> &nbsp;
                        Back to List
                    </button>
                </div>
            </div>
        </div>



    </div>
}

<script language="javascript" type="text/javascript">
    function h(e) {
        $(e).css({ 'height': 'auto', 'overflow-y': 'hidden' }).height(e.scrollHeight);
    }
    $('textarea').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>

Camada.Aplicacao/Views/LISTs/Index.cshtml
@model Camada.Dominio.Mensagens.TelaLISTs

@{
    ViewBag.Title = "Index";
}
<h2><i class="fa fa-search"></i> Search</h2>
<div class="form-horizontal">
    <h4>Check Limit Guest</h4>
</div>
<div style="padding-bottom: 40px; padding-top: 10px;">
    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("CreateBlacklist", "LISTs")'"
            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-file-o"></i> &nbsp;
                            Create Blacklist New
                    </button>
</div>
<div style="padding-bottom: 40px; padding-top: 10px;">
    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("CreateVerifyBooking", "LISTs")'"
            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-file-o"></i> &nbsp;
                            Create Limit Guest New
                    </button>
</div>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-13">
                    <label for="txtCopied" class="col-sm-1 control-label">Past the Sheet here:</label>
                    <div class="col-sm-10">
                        @Html.TextArea("txtCopied", new { htmlAttributes = new { @class = "form-control pastSheet" }, @cols = 140 })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Exec Report
                    </button>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">

    function h(e) {
        $(e).css({'height':'auto','overflow-y':'hidden'}).height(e.scrollHeight);
    }
    $('textarea').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>