Camada.Aplicacao/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Camada.Dominio.Entidades;
using System.Collections;
using System.Web.Script.Serialization;
using Library.Utilities;
using Camada.Dominio;
using Library.Messages;
using Camada.Dominio.Mensagens;
using System.ComponentModel.DataAnnotations;

namespace Camada.Aplicacao.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private HostelEntities db = new HostelEntities();

        public void ShowDialogMessage(TabDialogMessage dialogMessage, string message)
        {
            if (dialogMessage.ToString() == TabDialogMessage.Danger.ToString())
            {
                ViewBag.StatusDanger = message;
                ModelState.AddModelError("", message);
            }
            else if (dialogMessage.ToString() == TabDialogMessage.Sucess.ToString())
                ViewBag.StatusSucess = message;
            else if (dialogMessage.ToString() == TabDialogMessage.Info.ToString())
            {
                ViewBag.StatusInfo = message;
                ModelState.AddModelError("", message);
            }
            else if (dialogMessage.ToString() == TabDialogMessage.Warning.ToString())
            {
                ViewBag.StatusWarning = message;
                ModelState.AddModelError("", message);
            }
        }

        // GET: Transactions
        public ActionResult Index()
        {
            carregaCombos();

            return View();
        }

        public void carregaCombos()
        {
            var cmbReport_Type = db.Report_Type
                        .Where(w => w.ID != (int)TabReport_Type.Bank)
                        .Select(x =>
                                  new DropDownlist()
                                  {
                                      Value = x.ID,
                                      Text = x.Description
                                  }).ToList();

            var dropDownlist = new Camada.Dominio.Mensagens.DropDownlist();
            cmbReport_Type.Add(dropDownlist.AdicionarSelecione());
            ViewBag.cmbReport_Type = new SelectList(cmbReport_Type.OrderBy(o => o.Value), "Value", "Text");

            var cmbSHIFT_TYPE = db.SHIFT_TYPE
                        .Select(x =>
                                  new DropDownlist()
                                  {
                                      Value = x.ID,
                                      Text = x.DESCRIPTION
                                  }).ToList();

            ViewBag.cmbSHIFT_TYPE = new SelectList(cmbSHIFT_TYPE.OrderBy(o => o.Value), "Value", "Text");

        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var msg = Fachada.Repositorio.TOTAL_TRANSACTIONS.GetTotalTransactionByID(id.Value);
            if (msg.Result != Message.ResultType.Success)
                return Content(msg.Description);
            if (msg.Instance == null)
                return HttpNotFound();

            return RedirectToAction("Details", "TotalTransactions", new { id = id });
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            TelaTransactions trans = new TelaTransactions();
            carregaCombos();
            var msgTotalLastCalc = Fachada.Repositorio.CALC.GetTotalLastCalc();
            if (msgTotalLastCalc != null)
            {
                trans.ID_Last_Calc = msgTotalLastCalc.Instance.ID;
                trans.TotalCalc = msgTotalLastCalc.Instance.Total;
            }

            var msgTotalLastCashier = Fachada.Repositorio.TOTAL_TRANSACTIONS.GetLastTotal_Transaction();
            if (msgTotalLastCashier != null && msgTotalLastCashier.Instance != null && msgTotalLastCashier.Instance.TotalFinal.HasValue)
            {
                trans.ID_Last_Transaction = msgTotalLastCashier.Instance.ID;
                trans.TotalLastCashier = msgTotalLastCashier.Instance.TotalFinal.Value;
            }

            var msgTotalLastCashierVagner = Fachada.Repositorio.TOTAL_TRANSACTIONS.GetLastTotal_Vagner();
            if (msgTotalLastCashierVagner != null && msgTotalLastCashierVagner.Instance != null && msgTotalLastCashierVagner.Instance.TotalFinal.HasValue)
            {
                trans.ID_Last_TransactionVagner = msgTotalLastCashierVagner.Instance.ID;
                trans.TotalLastCashierVagner = msgTotalLastCashierVagner.Instance.TotalFinal.Value;
            }

            var msgTotalLastCashierCard = Fachada.Repositorio.TOTAL_TRANSACTIONS.GetLastTotal_Card();
            if (msgTotalLastCashierCard != null && msgTotalLastCashierCard.Instance != null && msgTotalLastCashierCard.Instance.TotalFinal.HasValue)
            {
                trans.ID_Last_TransactionCard = msgTotalLastCashierCard.Instance.ID;
                trans.TotalLastCashierCard = msgTotalLastCashierCard.Instance.TotalFinal.Value;
            }

            return View(trans);
        }

        public ActionResult CreateStart()
        {
            carregaCombos();
            return View();
        }
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateStart(Total_Transactions transaction)
        {
            if (ModelState.IsValid)
            {
                decimal txtTotal = Convert.ToDecimal(Request["TotalFinal"]);

                var totalTransaction = new Total_Transactions();
                totalTransaction.ID_Report_Type = (int)TabReport_Type.Cash;
                totalTransaction.TotalFinal = txtTotal;
                totalTransaction.LogLogin = (User != null && User.Identity != null && !string.IsNullOrEmpty(User.Identity.Name)) ? User.Identity.Name : string.Empty;
                totalTransaction.DT_Reg = DateTime.UtcNow;
                int idLasCashier = 0, idLastCalc = 0;
                decimal totalLastCashier = 0, totalLastCalc = 0;

                var msgTotalLastCalc = Fachada.Repositorio.CALC.GetTotalLastCalc();
                if (msgTotalLastCalc != null)
                {
                    totalLastCalc = msgTotalLastCalc.Instance.Total;
                    idLastCalc = msgTotalLastCalc.Instance.ID;
                }
                var msgTotalLastCashier = Fachada.Repositorio.TOTAL_TRANSACTIONS.GetLastTotal_Transaction();
                if (msgTotalLastCashier != null && msgTotalLastCashier.Instance != null && msgTotalLastCashier.Instance.TotalFinal.HasValue)
                {
                    totalLastCashier = msgTotalLastCashier.Instance.TotalFinal.Value;
                    idLasCashier = msgTotalLastCashier.Instance.ID;
                    totalTransaction.ID_Last_Transaction = idLasCashier;
                }

                totalTransaction.DifferenceFinalCalc = totalLastCalc - txtTotal;
                totalTransaction.TotalTransactions = txtTotal;
                totalTransaction.ID_Calc = idLastCalc;

                var msgSaveTotal_Transactions = Fachada.Negocio.ManterTOTAL_TRANSACTIONS.Salvar(totalTransaction);
                if (msgSaveTotal_Transactions.Result != Message.ResultType.Success)
                    return Content(msgSaveTotal_Transactions.Description);


                List<Transaction> listTrans = new List<Transaction>();
                Transaction trans = new Transaction();
                trans.DT_Reg = DateTime.UtcNow;
                trans.LogLogin = User.Identity.Name;
                trans.Reservation_Number = string.Empty;
                trans.GuestName = string.Empty;
                trans.Total = txtTotal;
                trans.ID_Transaction_Type = (int)TabTransaction_Type.Payment;
                trans.ID_Payment_Type = (int)TabPayment_Type.Cash;
                trans.ID_Total_Transactions = totalTransaction.ID;
                trans.Description = string.Empty;
                listTrans.Add(trans);
                var msgSaveTransactions = Fachada.Negocio.ManterTRANSACTIONS.SaveList(listTrans.ToArray());
                if (msgSaveTransactions.Result != Message.ResultType.Success)
                    return Content(msgSaveTransactions.Description);

                return RedirectToAction("Details", "TotalTransactions", new { id = totalTransaction.ID });
            }
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cmbSHIFT_TYPE, cmbReport_Type, txtCopied, ID_Last_Calc, TotalCalc, ID_Last_Transaction, TotalLastCashier, ID_Last_TransactionVagner, TotalLastCashierVagner, ID_Last_TransactionCard, TotalLastCashierCard")] Dominio.Mensagens.TelaTransactions transaction)
        {
            if (string.IsNullOrEmpty(transaction.txtCopied))
                ShowDialogMessage(TabDialogMessage.Danger, "Please, fill out the field: 'Past the Sheet here'");
            if (transaction.cmbReport_Type == 0)
                ShowDialogMessage(TabDialogMessage.Danger, "Please, select the Report Type");

            if (ModelState.IsValid)
            {
                string txtCopied = Convert.ToString(Request["txtCopied"]);

                int cmbReport_Type = Convert.ToInt32(Request["cmbReport_Type"]);
                decimal totalTransactions = 0;

Camada.Aplicacao/Views/Transactions/Create.cshtml
@model Camada.Dominio.Mensagens.TelaTransactions

@{
    ViewBag.Title = "Create";
}
<h2><i class="fa fa-pencil"></i> Create</h2>
<div class="form-horizontal">
    <h4>Transaction</h4>
    <hr />
</div>


@using (Html.BeginForm("Create", "Transactions", FormMethod.Post, new { id = "frmTransactions" }))
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.TotalCalc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.HiddenFor(model => model.ID_Last_Calc)
                    @Html.EditorFor(model => model.TotalCalc, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       @readonly = "readonly"
                   }
               })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TotalLastCashier, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.HiddenFor(model => model.ID_Last_Transaction)
                    @Html.EditorFor(model => model.TotalLastCashier, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       @readonly = "readonly"
                   }
               })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TotalLastCashierCard, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.HiddenFor(model => model.ID_Last_TransactionCard)
                    @Html.EditorFor(model => model.TotalLastCashierCard, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       @readonly = "readonly"
                   }
               })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TotalLastCashierVagner, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.HiddenFor(model => model.ID_Last_TransactionVagner)
                    @Html.EditorFor(model => model.TotalLastCashierVagner, new
               {
                   htmlAttributes = new
                   {
                       @class = "form-control",
                       @readonly = "readonly"
                   }
               })
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="col-md-13">
                    <label for="txtCopied" class="col-sm-1 control-label">Past the Sheet here:</label>
                    <div class="col-sm-10">
                        @Html.TextArea("txtCopied", new { htmlAttributes = new { @class = "form-control pastSheet" }, @cols = 140 })
                        @*<input type="text" style="width: 900px;" name="txtCopied" class="form-control sm" id="txtCopied" required>*@
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-13">
                    <label for="cmbSHIFT_TYPE" class="col-sm-2 control-label">Shift Type</label>
                    <div class="col-sm-2">
                        @Html.DropDownList("cmbSHIFT_TYPE", (IEnumerable<SelectListItem>)ViewBag.cmbSHIFT_TYPE, new { @class = "form-control input-sm" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-13">
                    <label for="cmbReport_Type" class="col-sm-2 control-label">Report Type</label>
                    <div class="col-sm-2">
                        @Html.DropDownList("cmbReport_Type", (IEnumerable<SelectListItem>)ViewBag.cmbReport_Type, new { @class = "form-control input-sm" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Exec Report
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("Index", "Transactions")'"
                            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-arrow-left"></i> &nbsp;
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">
    $('#frmTransactions').submit(function () {
        var totalCalc = $('#TotalCalc').val().replace(/€/g, '').replace(/\,/g, '');
        $('#TotalCalc').val(totalCalc);
        var totalLastCashier = $('#TotalLastCashier').val().replace(/€/g, '').replace(/\,/g, '');
        $('#TotalLastCashier').val(totalLastCashier);
        var totalLastCashierCard = $('#TotalLastCashierCard').val().replace(/€/g, '').replace(/\,/g, '');
        $('#TotalLastCashierCard').val(totalLastCashierCard);
        var totalLastCashierVagner = $('#TotalLastCashierVagner').val().replace(/€/g, '').replace(/\,/g, '');
        $('#TotalLastCashierVagner').val(totalLastCashierVagner);
        $('#frmTransactions').submit();
        return false;
    });

    //$('#cmbReport_Type').change(function () {
    //    $('#TotalLastCashierVagner').val("");
    //    if ($('#cmbReport_Type').val() == 3 || $('#cmbReport_Type').val() == 4)
    //        $('#TotalLastCashierVagner').removeAttr('disabled');
    //    else
    //        $('#TotalLastCashierVagner').attr('disabled', 'disabled');
    //});

    //$('#txtCopied').change(function () {
    //    var text = document.getElementById('text');
    //    function resize () {
    //        text.style.height = 'auto';
    //        text.style.height = text.scrollHeight+'px';
    //    }
    //    /* 0-timeout to get the already changed text */
    //    function delayedResize () {
    //        window.setTimeout(resize, 0);
    //    }
    //    observe(text, 'change',  resize);
    //    observe(text, 'cut',     delayedResize);
    //    observe(text, 'paste',   delayedResize);
    //    observe(text, 'drop',    delayedResize);
    //    observe(text, 'keydown', delayedResize);

    //    text.focus();
    //    text.select();
    //    resize();
    //});

    //var observe;
    //if (window.attachEvent) {
    //    observe = function (element, event, handler) {
    //        element.attachEvent('on'+event, handler);
    //    };
    //}
    ////else {
    ////    observe = function (element, event, handler) {
    ////        element.addEventListener(event, handler, false);
    ////    };
    //}

    function h(e) {
        $(e).css({ 'height': 'auto', 'overflow-y': 'hidden' }).height(e.scrollHeight);
    }
    $('textarea').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Camada.Aplicacao/Views/Transactions/CreateStart.cshtml
@model Camada.Dominio.Mensagens.TelaTransactions

@{
    ViewBag.Title = "Create";
}
<h2><i class="fa fa-pencil"></i> Create START</h2>
<div class="form-horizontal">
    <h4>Transaction</h4>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel-body">
        <div class="form-horizontal">

            <hr />
            <div class="form-group">
                @Html.LabelFor(model => model.TotalFinal, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.TotalFinal, new { htmlAttributes = new { @class = "form-control onlyMoney", requerid = "required" } })
                    @Html.ValidationMessageFor(model => model.TotalFinal, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-5">
                    <button type="submit" class="btn btn-default btn-sm pull-left" title="Exec Report" value="btnExecReport" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-floppy-o"></i> &nbsp;
                        Create
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5">
                    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("Index", "Transactions")'"
                            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-arrow-left"></i> &nbsp;
                        Back to List
                    </button>
                </div>
            </div>
        </div>
    </div>
}
<script language="javascript" type="text/javascript">

    $('#cmbReport_Type').change(function () {
        $('#TotalLastCashierVagner').val("");
        if ($('#cmbReport_Type').val() == 3)
            $('#TotalLastCashierVagner').removeAttr('disabled');
        else
            $('#TotalLastCashierVagner').attr('disabled', 'disabled');
    });

    //$('#txtCopied').change(function () {
    //    var text = document.getElementById('text');
    //    function resize () {
    //        text.style.height = 'auto';
    //        text.style.height = text.scrollHeight+'px';
    //    }
    //    /* 0-timeout to get the already changed text */
    //    function delayedResize () {
    //        window.setTimeout(resize, 0);
    //    }
    //    observe(text, 'change',  resize);
    //    observe(text, 'cut',     delayedResize);
    //    observe(text, 'paste',   delayedResize);
    //    observe(text, 'drop',    delayedResize);
    //    observe(text, 'keydown', delayedResize);

    //    text.focus();
    //    text.select();
    //    resize();
    //});

    //var observe;
    //if (window.attachEvent) {
    //    observe = function (element, event, handler) {
    //        element.attachEvent('on'+event, handler);
    //    };
    //}
    ////else {
    ////    observe = function (element, event, handler) {
    ////        element.addEventListener(event, handler, false);
    ////    };
    //}

    function h(e) {
        $(e).css({'height':'auto','overflow-y':'hidden'}).height(e.scrollHeight);
    }
    $('textarea').each(function () {
        h(this);
    }).on('input', function () {
        h(this);
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Camada.Aplicacao/Views/Transactions/Index.cshtml
@model IEnumerable<Camada.Dominio.Mensagens.GridTotalTransactionIndex>

@{
    ViewBag.Title = "Index";
}

<h2><i class="fa fa-search"></i> Search</h2>
<div class="form-horizontal">
    @*<span style="float: right;">
        <a style="cursor:pointer"
           href="@Url.Action("Index", "Transactions")"
           title="Atualizar Página">
            <i class="fa fa-refresh fa-spin" style="margin-right: 2px;"></i>
        </a>
    </span>*@
    <h4>Transactions</h4>
</div>
<div style="padding-bottom: 40px; padding-top: 10px;">
    <button type="button" class="btn btn-default btn-sm pull-left" onclick="location.href='@Url.Action("Create", "Transactions")'"
            data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Copied ">
                        <i class="fa fa-file-o"></i> &nbsp;
                            Create New
                    </button>
</div>
<hr />
<form id="frmPesquisa" class="form-horizontal" role="form">

    @Html.ValidationSummary(true)

    <div class="form-group">
        <div class="col-md-13">
            <label for="txtDtInicio" class="col-sm-1 control-label">Data Início</label>
            <div class="col-sm-1">
                <input type="text" name="txtDtInicio" class="form-control input-sm dateTextField" id="txtDtInicio" required />
            </div>

            <label for="cmbReport_Type" class="col-md-2 control-label">Report Type</label>
            <div class="col-sm-2">
                @Html.DropDownList("cmbReport_Type", (IEnumerable<SelectListItem>)ViewBag.cmbReport_Type, new { @class = "form-control input-sm" })
            </div>

            @*<label for="cmbPayment_Type" class="col-sm-2 control-label">Payment Type</label>
                <div class="col-sm-3">
                    @Html.DropDownList("cmbPayment_Type", (IEnumerable<SelectListItem>)ViewBag.cmbPayment_Type, new { @class = "form-control input-sm" })
                </div>*@
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-10">
            <label for="txtDtFim" class="col-sm-1 control-label">Data Fim</label>
            <div class="col-sm-1">
                <input type="text" name="txtDtFim" class="form-control input-sm dateTextField" id="txtDtFim" required />
            </div>

            <label for="txtNome" class="col-sm-2 control-label">Nome</label>
            <div class="col-sm-4">
                <input type="text" name="txtNome" class="form-control input-sm" id="txtNome" required />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-0 col-sm-12">
            <div class="barraComando">
                </a>
                <button type="submit" class="btn btn-default btn-sm pull-right" title="Search" id="btnPesquisar" data-loading-text="
                        <i class='fa fa-circle-o-notch fa-spin'></i> Search ">
                        <i class="fa fa-search"></i> &nbsp;
                        Pesquisar
                    </button>

                <a class="btn btn-default btn-sm pull-right" title="Clean" id="btnLimpar" data-loading-text="
                        <i class='fa fa-eraser'></i> Clean">
                        <i class="fa fa-eraser"></i> &nbsp;
                        Limpar
                    </a>
            </div>
        </div>
    </div>
</form>

<div class="table-responsive">
    <table id="gridTransactions" class="table table-striped table-bordered table-hover table-responsive dataTable no-footer" cellspacing="0" style=" overflow scroll;">
        <thead class="sorted_head">
            <tr>
                <th></th>
                <th width="130px">
                    @Html.DisplayNameFor(model => model.DT_Reg)
                </th>
                <th width="70px">
                    @Html.DisplayNameFor(model => model.DESCRIPTION_SHIFT_TYPE)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LogLogin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalTransactions)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastTotalCashier)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalFinal)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TotalCalc)
                </th>
                <th width="100px">
                    @Html.DisplayNameFor(model => model.DifferenceFinalCalc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Desc_Report_Type)
                </th>
                <th width="70px">
                </th>
            </tr>
        </thead>
        <tbody></tbody>
        <tfoot>

        </tfoot>
    </table>
</div>


<script language="javascript" type="text/javascript">

    var filtro = (new function () {
        var self = this;

        this.tabela = null;
        this.URL = '';
        this.idPayment_Type = null;
        this.txtNome = null;
        this.dtInicio = null;
        this.dtFim = null;

        this.carregar = function () {
            try {
                self.idPayment_Type = $("#cmbPayment_Type").val();
                self.txtNome = $("#txtDtInicio").val();
                self.dtInicio = $("#txtDtFim").val();
                self.dtFim = $("#txtNome").val();
                self.getDataTable().draw();
            }
            catch (e) {
                console.log(e);
            }
            return false;
        };

        this.getDataTable = function () {
            return self.tabela.DataTable();
        };

        this.editar = function () {
            var data = self.getDataTable().row($(this).parents('tr')).data();
            var url = '@Url.Action("Details", "Transactions")';
            url = url + '/' + data[0];
            window.location.assign(url);
        };

        this.remover = function (e) {
            var data = self.getDataTable().row($(this).parents('tr')).data();
            var url = '@Url.Action("Delete", "TotalTransactions")';
            url = url + '/' + data[0];
            window.location.assign(url);
        };

        this.init = function () {
            self.tabela = $('#gridTransactions');

            self.tabela.DataTable({
                "language": {
                    "url": "/Scripts/DataTables/Portuguese-Brasil.txt"
                },
                stateSave: true,
                "searching": true,
                "dom": 'rt<"bottom"lp<"clear">>',
                "bServerSide": true,
                "bProcessing": true,
                "bSort": true,
                "sPaginationType": "full_numbers",
                "sAjaxSource": self.URL,
                "columnDefs": [
                     {
                         "targets": [0],
                         "visible": false,
                         "searchable": false
                     },
                       {
                           "targets": -1,
                           "data": null,
                           "bSortable": false,
                           "defaultContent": "&nbsp;<i title='Detail' class='fa fa-edit fa-lg btnEditar corIconeEditar'></i> <i title='Delete' class='fa fa-trash fa-lg text-danger btnCancelar'></i> "
                           //"defaultContent": "nda ainda"
                       }
                ],
                serverParams: function (aoData) {
                    $.each($("form").serializeArray(), function (indice, dados) {
                        aoData.push(dados);
                    });
                    aoData.push({ "name": "myParam", "value": "myValue" });
                }
            }).on('processing.dt', function (e, settings, processing) {
                var valor = $(this).val();
                var btn = $('#btnExecReport');
                //processing ? btn.button('loading') : btn.button('reset');
            });

            $('#gridTransactions tbody').on('click', '.btnEditar', self.editar);
            $('#gridTransactions tbody').on('click', '.btnCancelar', self.remover);
            $('#btnPesquisar').on('click', self.carregar);

            $('#btnLimpar').on('click', function () {
                //var $btn = $(this).button('loading');
                self.idPayment_Type = $("#cmbPayment_Type").val(0);
                self.txtNome = $("#txtNome").val("");
                self.dtInicio = $("#txtDtInicio").val("");
                self.dtFim = $("#txtDtFim").val("");
                self.carregar();
                //$btn.button('reset');
                $('#btnLimpar').hide();
            });

            //$('#btnPesquisar').on('click', self.carregar);
        };

        return this;
    });

    filtro.URL = '@Url.Action("getGridTransaction", "Transactions")';
    $(filtro.init);
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



